//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_SsoftTotalTrip.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mmh.totaltrip.com/webservice/HotelCancelService.asmx")]
        public string WS_SsoftTotalTrip_CancelHotel_HotelCancelService {
            get {
                return ((string)(this["WS_SsoftTotalTrip_CancelHotel_HotelCancelService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mmh.totaltrip.com/webservice/HotelInfoService.asmx")]
        public string WS_SsoftTotalTrip_GetHotelInfos_HotelInfoService {
            get {
                return ((string)(this["WS_SsoftTotalTrip_GetHotelInfos_HotelInfoService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mmh.totaltrip.com/webservice/HotelReservationInfoService.asmx")]
        public string WS_SsoftTotalTrip_HotelReservationInfo_HotelReservationInfoService {
            get {
                return ((string)(this["WS_SsoftTotalTrip_HotelReservationInfo_HotelReservationInfoService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mmh.totaltrip.com/webservice/HotelConfirmService.asmx")]
        public string WS_SsoftTotalTrip_HotelConfirm_HotelConfirmService {
            get {
                return ((string)(this["WS_SsoftTotalTrip_HotelConfirm_HotelConfirmService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mmh.totaltrip.com/webservice/HotelResService.asmx")]
        public string WS_SsoftTotalTrip_HotelRes_HotelResService {
            get {
                return ((string)(this["WS_SsoftTotalTrip_HotelRes_HotelResService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://mmh.totaltrip.com/webservice/HotelShopService.asmx")]
        public string WS_SsoftTotalTrip_HotelShop_HotelShopService {
            get {
                return ((string)(this["WS_SsoftTotalTrip_HotelShop_HotelShopService"]));
            }
        }
    }
}
