//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18444.
// 
#pragma warning disable 1591

namespace WS_SsoftTotalTrip.GetHotelInfos {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="HotelInfoServiceSoap", Namespace="http://www.totaltrip.com")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(WSSecurity))]
    public partial class HotelInfoService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetHotelInfosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public HotelInfoService() {
            this.Url = global::WS_SsoftTotalTrip.Properties.Settings.Default.WS_SsoftTotalTrip_GetHotelInfos_HotelInfoService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetHotelInfosCompletedEventHandler GetHotelInfosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.totaltrip.com/GetHotelInfos", RequestNamespace="http://www.totaltrip.com", ResponseNamespace="http://www.totaltrip.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public HotelInfoRS GetHotelInfos(HotelInfoRQ rq) {
            object[] results = this.Invoke("GetHotelInfos", new object[] {
                        rq});
            return ((HotelInfoRS)(results[0]));
        }
        
        /// <remarks/>
        public void GetHotelInfosAsync(HotelInfoRQ rq) {
            this.GetHotelInfosAsync(rq, null);
        }
        
        /// <remarks/>
        public void GetHotelInfosAsync(HotelInfoRQ rq, object userState) {
            if ((this.GetHotelInfosOperationCompleted == null)) {
                this.GetHotelInfosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetHotelInfosOperationCompleted);
            }
            this.InvokeAsync("GetHotelInfos", new object[] {
                        rq}, this.GetHotelInfosOperationCompleted, userState);
        }
        
        private void OnGetHotelInfosOperationCompleted(object arg) {
            if ((this.GetHotelInfosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetHotelInfosCompleted(this, new GetHotelInfosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.totaltrip.com")]
    public partial class HotelInfoRQ : WSSecurity {
        
        private string cityCodeField;
        
        private int[] hotelCodesField;
        
        private string languageField;
        
        private int sourceField;
        
        /// <comentarios/>
        public string CityCode {
            get {
                return this.cityCodeField;
            }
            set {
                this.cityCodeField = value;
            }
        }
        
        /// <comentarios/>
        public int[] HotelCodes {
            get {
                return this.hotelCodesField;
            }
            set {
                this.hotelCodesField = value;
            }
        }
        
        /// <comentarios/>
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <comentarios/>
        public int Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(HotelInfoRQ))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.totaltrip.com")]
    public abstract partial class WSSecurity {
        
        private string usernameField;
        
        private string passwordField;
        
        /// <comentarios/>
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <comentarios/>
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.totaltrip.com")]
    public partial class Hotel {
        
        private string addressField;
        
        private string chainCodeField;
        
        private int hotelIdField;
        
        private int hotelCodeField;
        
        private string hotelNameField;
        
        private int sourceField;
        
        private string phoneField;
        
        private string descriptionField;
        
        private string longDescriptionField;
        
        private string propertyMessageField;
        
        private string cityCodeField;
        
        private string ratingField;
        
        private string latitudeField;
        
        private string longitudeField;
        
        private string localityField;
        
        private string neighborhoodField;
        
        private string area1Field;
        
        private string area2Field;
        
        private int confidenceFactorField;
        
        private string[] ammenitiesField;
        
        private string[] imagesField;
        
        /// <comentarios/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <comentarios/>
        public string ChainCode {
            get {
                return this.chainCodeField;
            }
            set {
                this.chainCodeField = value;
            }
        }
        
        /// <comentarios/>
        public int HotelId {
            get {
                return this.hotelIdField;
            }
            set {
                this.hotelIdField = value;
            }
        }
        
        /// <comentarios/>
        public int HotelCode {
            get {
                return this.hotelCodeField;
            }
            set {
                this.hotelCodeField = value;
            }
        }
        
        /// <comentarios/>
        public string HotelName {
            get {
                return this.hotelNameField;
            }
            set {
                this.hotelNameField = value;
            }
        }
        
        /// <comentarios/>
        public int Source {
            get {
                return this.sourceField;
            }
            set {
                this.sourceField = value;
            }
        }
        
        /// <comentarios/>
        public string Phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
            }
        }
        
        /// <comentarios/>
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <comentarios/>
        public string LongDescription {
            get {
                return this.longDescriptionField;
            }
            set {
                this.longDescriptionField = value;
            }
        }
        
        /// <comentarios/>
        public string PropertyMessage {
            get {
                return this.propertyMessageField;
            }
            set {
                this.propertyMessageField = value;
            }
        }
        
        /// <comentarios/>
        public string CityCode {
            get {
                return this.cityCodeField;
            }
            set {
                this.cityCodeField = value;
            }
        }
        
        /// <comentarios/>
        public string Rating {
            get {
                return this.ratingField;
            }
            set {
                this.ratingField = value;
            }
        }
        
        /// <comentarios/>
        public string Latitude {
            get {
                return this.latitudeField;
            }
            set {
                this.latitudeField = value;
            }
        }
        
        /// <comentarios/>
        public string Longitude {
            get {
                return this.longitudeField;
            }
            set {
                this.longitudeField = value;
            }
        }
        
        /// <comentarios/>
        public string Locality {
            get {
                return this.localityField;
            }
            set {
                this.localityField = value;
            }
        }
        
        /// <comentarios/>
        public string Neighborhood {
            get {
                return this.neighborhoodField;
            }
            set {
                this.neighborhoodField = value;
            }
        }
        
        /// <comentarios/>
        public string Area1 {
            get {
                return this.area1Field;
            }
            set {
                this.area1Field = value;
            }
        }
        
        /// <comentarios/>
        public string Area2 {
            get {
                return this.area2Field;
            }
            set {
                this.area2Field = value;
            }
        }
        
        /// <comentarios/>
        public int ConfidenceFactor {
            get {
                return this.confidenceFactorField;
            }
            set {
                this.confidenceFactorField = value;
            }
        }
        
        /// <comentarios/>
        public string[] Ammenities {
            get {
                return this.ammenitiesField;
            }
            set {
                this.ammenitiesField = value;
            }
        }
        
        /// <comentarios/>
        public string[] Images {
            get {
                return this.imagesField;
            }
            set {
                this.imagesField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.totaltrip.com")]
    public partial class HotelInfoRS {
        
        private Hotel[] hotelInfosField;
        
        /// <comentarios/>
        public Hotel[] HotelInfos {
            get {
                return this.hotelInfosField;
            }
            set {
                this.hotelInfosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetHotelInfosCompletedEventHandler(object sender, GetHotelInfosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetHotelInfosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetHotelInfosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public HotelInfoRS Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((HotelInfoRS)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591