#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 09-10-07 04:35 p.m.
//
// This source code was auto-generated by WSCF, Version=0.6.6034.1
#endregion


namespace WebService_AddRemarkLLS
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    public interface IAddRemarkService
    {
        
        AddRemarkRS AddRemarkRQ(AddRemarkRQ addRemarkRQ1);
    }
}
