#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 22-08-07 11:03 a.m.
//
// This source code was auto-generated by WSCF, Version=0.6.6034.1
#endregion


namespace WebService_TravelItineraryAddInfoLLS
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    public interface ITravelItineraryAddInfoService
    {
        
        TravelItineraryAddInfoRS TravelItineraryAddInfoRQ(TravelItineraryAddInfoRQ travelItineraryAddInfoRQ1);
    }
}
