#region WSCF
//------------------------------------------------------------------------------
// <autogenerated code>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated code>
//------------------------------------------------------------------------------
// File time 09-10-07 04:35 p.m.
//
// This source code was auto-generated by WSCF, Version=0.6.6034.1
#endregion


namespace WebService_AddRemarkLLS
{
    using System.Diagnostics;
    using System.Web.Services;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AddRemarkSoapBinding", Namespace="https://webservices.sabre.com/websvc")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Fault))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Envelope))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SignaturePropertiesType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ManifestType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(SignatureType))]
    public partial class AddRemarkService : System.Web.Services.Protocols.SoapHttpClientProtocol, IAddRemarkService
    {
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="MessageHeaderValue")]
        public MessageHeader MessageHeaderValue;
        
        [System.Xml.Serialization.XmlElementAttribute(ElementName="SecurityValue")]
        public Security SecurityValue;
        
        private System.Threading.SendOrPostCallback AddRemarkRQOperationCompleted;
        
        /// <remarks/>
        public AddRemarkService()
        {
            this.Url = "https://webservices.sabre.com/websvc";
        }
        
        /// <remarks/>
        public event AddRemarkRQCompletedEventHandler AddRemarkRQCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MessageHeaderValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("SecurityValue", Direction=System.Web.Services.Protocols.SoapHeaderDirection.InOut)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("OTA", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("AddRemarkRS", Namespace="http://webservices.sabre.com/sabreXML/2003/07")]
        public AddRemarkRS AddRemarkRQ([System.Xml.Serialization.XmlElementAttribute("AddRemarkRQ", Namespace="http://webservices.sabre.com/sabreXML/2003/07")] AddRemarkRQ addRemarkRQ1)
        {
            object[] results = this.Invoke("AddRemarkRQ", new object[] {
                        addRemarkRQ1});
            return ((AddRemarkRS)(results[0]));
        }
        
        /// <remarks/>
        public void AddRemarkRQAsync(AddRemarkRQ addRemarkRQ1)
        {
            this.AddRemarkRQAsync(addRemarkRQ1, null);
        }
        
        /// <remarks/>
        public void AddRemarkRQAsync(AddRemarkRQ addRemarkRQ1, object userState)
        {
            if ((this.AddRemarkRQOperationCompleted == null))
            {
                this.AddRemarkRQOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddRemarkRQOperationCompleted);
            }
            this.InvokeAsync("AddRemarkRQ", new object[] {
                        addRemarkRQ1}, this.AddRemarkRQOperationCompleted, userState);
        }
        
        private void OnAddRemarkRQOperationCompleted(object arg)
        {
            if ((this.AddRemarkRQCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddRemarkRQCompleted(this, new AddRemarkRQCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ebxml.org/namespaces/messageHeader", TypeName="MessageHeader")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.ebxml.org/namespaces/messageHeader", IsNullable=false)]
    public partial class MessageHeader : System.Web.Services.Protocols.SoapHeader
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="From")]
        public From From;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="To")]
        public To To;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="CPAId")]
        public string CPAId;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="ConversationId")]
        public string ConversationId;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Service")]
        public Service Service;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Action")]
        public string Action;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="MessageData")]
        public MessageData MessageData;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="DuplicateElimination")]
        public object DuplicateElimination;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("Description")]
        public Description[] Description;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="ID", AttributeName="id")]
        public string id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, AttributeName="version")]
        public string version;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr;
        
        public MessageHeader()
        {
        }
        
        public MessageHeader(From from, To to, string cPAId, string conversationId, Service service, string action, MessageData messageData, object duplicateElimination, Description[] description, System.Xml.XmlElement[] any, string id, string version, System.Xml.XmlAttribute[] anyAttr)
        {
            this.From = from;
            this.To = to;
            this.CPAId = cPAId;
            this.ConversationId = conversationId;
            this.Service = service;
            this.Action = action;
            this.MessageData = messageData;
            this.DuplicateElimination = duplicateElimination;
            this.Description = description;
            this.Any = any;
            this.id = id;
            this.version = version;
            this.AnyAttr = anyAttr;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ebxml.org/namespaces/messageHeader", TypeName="From")]
    public partial class From
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("PartyId")]
        public PartyId[] PartyId;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Role")]
        public string Role;
        
        public From()
        {
        }
        
        public From(PartyId[] partyId, string role)
        {
            this.PartyId = partyId;
            this.Role = role;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ebxml.org/namespaces/messageHeader", TypeName="PartyId")]
    public partial class PartyId
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, AttributeName="type")]
        public string type;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
        
        public PartyId()
        {
        }
        
        public PartyId(string type, string value)
        {
            this.type = type;
            this.Value = value;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/soap/envelope/", TypeName="detail")]
    public partial class detail
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr;
        
        public detail()
        {
        }
        
        public detail(System.Xml.XmlElement[] any, System.Xml.XmlAttribute[] anyAttr)
        {
            this.Any = any;
            this.AnyAttr = anyAttr;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/soap/envelope/", TypeName="Fault")]
    public partial class Fault
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName="faultcode")]
        public System.Xml.XmlQualifiedName faultcode;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName="faultstring")]
        public string faultstring;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", ElementName="faultactor")]
        public string faultactor;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName="detail")]
        public detail detail;
        
        public Fault()
        {
        }
        
        public Fault(System.Xml.XmlQualifiedName faultcode, string faultstring, string faultactor, detail detail)
        {
            this.faultcode = faultcode;
            this.faultstring = faultstring;
            this.faultactor = faultactor;
            this.detail = detail;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/soap/envelope/", TypeName="Body")]
    public partial class Body
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr;
        
        public Body()
        {
        }
        
        public Body(System.Xml.XmlElement[] any, System.Xml.XmlAttribute[] anyAttr)
        {
            this.Any = any;
            this.AnyAttr = anyAttr;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/soap/envelope/", TypeName="Header")]
    public partial class Header
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr;
        
        public Header()
        {
        }
        
        public Header(System.Xml.XmlElement[] any, System.Xml.XmlAttribute[] anyAttr)
        {
            this.Any = any;
            this.AnyAttr = anyAttr;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.xmlsoap.org/soap/envelope/", TypeName="Envelope")]
    public partial class Envelope
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("Header")]
        public Header[] Header;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Body")]
        public Body Body;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr;
        
        public Envelope()
        {
        }
        
        public Envelope(Header[] header, Body body, System.Xml.XmlElement[] any, System.Xml.XmlAttribute[] anyAttr)
        {
            this.Header = header;
            this.Body = body;
            this.Any = any;
            this.AnyAttr = anyAttr;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="SignaturePropertyType")]
    public partial class SignaturePropertyType
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Items;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI", AttributeName="Target")]
        public string Target;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID", AttributeName="Id")]
        public string Id;
        
        public SignaturePropertyType()
        {
        }
        
        public SignaturePropertyType(System.Xml.XmlElement[] items, string[] text, string target, string id)
        {
            this.Items = items;
            this.Text = text;
            this.Target = target;
            this.Id = id;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="SignaturePropertiesType")]
    public partial class SignaturePropertiesType
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("SignatureProperty")]
        public SignaturePropertyType[] SignatureProperty;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID", AttributeName="Id")]
        public string Id;
        
        public SignaturePropertiesType()
        {
        }
        
        public SignaturePropertiesType(SignaturePropertyType[] signatureProperty, string id)
        {
            this.SignatureProperty = signatureProperty;
            this.Id = id;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="ManifestType")]
    public partial class ManifestType
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("Reference")]
        public ReferenceType[] Reference;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID", AttributeName="Id")]
        public string Id;
        
        public ManifestType()
        {
        }
        
        public ManifestType(ReferenceType[] reference, string id)
        {
            this.Reference = reference;
            this.Id = id;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="ReferenceType")]
    public partial class ReferenceType
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false)]
        [System.Xml.Serialization.XmlArrayAttribute(ElementName="Transforms")]
        public TransformType[] Transforms;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="DigestMethod")]
        public DigestMethodType DigestMethod;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DigestValue;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID", AttributeName="Id")]
        public string Id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI", AttributeName="URI")]
        public string URI;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI", AttributeName="Type")]
        public string Type;
        
        public ReferenceType()
        {
        }
        
        public ReferenceType(TransformType[] transforms, DigestMethodType digestMethod, byte[] digestValue, string id, string uRI, string type)
        {
            this.Transforms = transforms;
            this.DigestMethod = digestMethod;
            this.DigestValue = digestValue;
            this.Id = id;
            this.URI = uRI;
            this.Type = type;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="TransformType")]
    public partial class TransformType
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("XPath", typeof(string))]
        public object[] Items;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI", AttributeName="Algorithm")]
        public string Algorithm;
        
        public TransformType()
        {
        }
        
        public TransformType(object[] items, string[] text, string algorithm)
        {
            this.Items = items;
            this.Text = text;
            this.Algorithm = algorithm;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="DigestMethodType")]
    public partial class DigestMethodType
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI", AttributeName="Algorithm")]
        public string Algorithm;
        
        public DigestMethodType()
        {
        }
        
        public DigestMethodType(System.Xml.XmlNode[] any, string algorithm)
        {
            this.Any = any;
            this.Algorithm = algorithm;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="ObjectType")]
    public partial class ObjectType
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID", AttributeName="Id")]
        public string Id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="MimeType")]
        public string MimeType;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI", AttributeName="Encoding")]
        public string Encoding;
        
        public ObjectType()
        {
        }
        
        public ObjectType(System.Xml.XmlNode[] any, string id, string mimeType, string encoding)
        {
            this.Any = any;
            this.Id = id;
            this.MimeType = mimeType;
            this.Encoding = encoding;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="SPKIDataType")]
    public partial class SPKIDataType
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("SPKISexp", DataType="base64Binary")]
        public byte[][] SPKISexp;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement Any;
        
        public SPKIDataType()
        {
        }
        
        public SPKIDataType(byte[][] sPKISexp, System.Xml.XmlElement any)
        {
            this.SPKISexp = sPKISexp;
            this.Any = any;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="PGPDataType")]
    public partial class PGPDataType
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] PGPKeyID;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] PGPKeyPacket;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any;
        
        public PGPDataType()
        {
        }
        
        public PGPDataType(byte[] pGPKeyID, byte[] pGPKeyPacket, System.Xml.XmlElement[] any)
        {
            this.PGPKeyID = pGPKeyID;
            this.PGPKeyPacket = pGPKeyPacket;
            this.Any = any;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="X509IssuerSerialType")]
    public partial class X509IssuerSerialType
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="X509IssuerName")]
        public string X509IssuerName;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", ElementName="X509SerialNumber")]
        public string X509SerialNumber;
        
        public X509IssuerSerialType()
        {
        }
        
        public X509IssuerSerialType(string x509IssuerName, string x509SerialNumber)
        {
            this.X509IssuerName = x509IssuerName;
            this.X509SerialNumber = x509SerialNumber;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="X509DataType")]
    public partial class X509DataType
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("X509CRL", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("X509Certificate", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("X509IssuerSerial", typeof(X509IssuerSerialType))]
        [System.Xml.Serialization.XmlElementAttribute("X509SKI", typeof(byte[]), DataType="base64Binary")]
        [System.Xml.Serialization.XmlElementAttribute("X509SubjectName", typeof(string))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName;
        
        public X509DataType()
        {
        }
        
        public X509DataType(object[] items, ItemsChoiceType[] itemsElementName)
        {
            this.Items = items;
            this.ItemsElementName = itemsElementName;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false, TypeName="ItemsChoiceType")]
    public enum ItemsChoiceType
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("##any:")]
        Item,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="X509CRL")]
        X509CRL,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="X509Certificate")]
        X509Certificate,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="X509IssuerSerial")]
        X509IssuerSerial,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="X509SKI")]
        X509SKI,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="X509SubjectName")]
        X509SubjectName,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="RetrievalMethodType")]
    public partial class RetrievalMethodType
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false)]
        [System.Xml.Serialization.XmlArrayAttribute(ElementName="Transforms")]
        public TransformType[] Transforms;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI", AttributeName="URI")]
        public string URI;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI", AttributeName="Type")]
        public string Type;
        
        public RetrievalMethodType()
        {
        }
        
        public RetrievalMethodType(TransformType[] transforms, string uRI, string type)
        {
            this.Transforms = transforms;
            this.URI = uRI;
            this.Type = type;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="RSAKeyValueType")]
    public partial class RSAKeyValueType
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Modulus;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Exponent;
        
        public RSAKeyValueType()
        {
        }
        
        public RSAKeyValueType(byte[] modulus, byte[] exponent)
        {
            this.Modulus = modulus;
            this.Exponent = exponent;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="DSAKeyValueType")]
    public partial class DSAKeyValueType
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] P;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Q;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] G;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Y;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] J;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] Seed;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] PgenCounter;
        
        public DSAKeyValueType()
        {
        }
        
        public DSAKeyValueType(byte[] p, byte[] q, byte[] g, byte[] y, byte[] j, byte[] seed, byte[] pgenCounter)
        {
            this.P = p;
            this.Q = q;
            this.G = g;
            this.Y = y;
            this.J = j;
            this.Seed = seed;
            this.PgenCounter = pgenCounter;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="KeyValueType")]
    public partial class KeyValueType
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("DSAKeyValue", typeof(DSAKeyValueType))]
        [System.Xml.Serialization.XmlElementAttribute("RSAKeyValue", typeof(RSAKeyValueType))]
        public object Item;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
        
        public KeyValueType()
        {
        }
        
        public KeyValueType(object item, string[] text)
        {
            this.Item = item;
            this.Text = text;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="KeyInfoType")]
    public partial class KeyInfoType
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("KeyName", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("KeyValue", typeof(KeyValueType))]
        [System.Xml.Serialization.XmlElementAttribute("MgmtData", typeof(string))]
        [System.Xml.Serialization.XmlElementAttribute("PGPData", typeof(PGPDataType))]
        [System.Xml.Serialization.XmlElementAttribute("RetrievalMethod", typeof(RetrievalMethodType))]
        [System.Xml.Serialization.XmlElementAttribute("SPKIData", typeof(SPKIDataType))]
        [System.Xml.Serialization.XmlElementAttribute("X509Data", typeof(X509DataType))]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID", AttributeName="Id")]
        public string Id;
        
        public KeyInfoType()
        {
        }
        
        public KeyInfoType(object[] items, ItemsChoiceType1[] itemsElementName, string[] text, string id)
        {
            this.Items = items;
            this.ItemsElementName = itemsElementName;
            this.Text = text;
            this.Id = id;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false, TypeName="ItemsChoiceType1")]
    public enum ItemsChoiceType1
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute("##any:")]
        Item,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="KeyName")]
        KeyName,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="KeyValue")]
        KeyValue,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="MgmtData")]
        MgmtData,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="PGPData")]
        PGPData,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="RetrievalMethod")]
        RetrievalMethod,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="SPKIData")]
        SPKIData,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="X509Data")]
        X509Data,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="SignatureValueType")]
    public partial class SignatureValueType
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID", AttributeName="Id")]
        public string Id;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value;
        
        public SignatureValueType()
        {
        }
        
        public SignatureValueType(string id, byte[] value)
        {
            this.Id = id;
            this.Value = value;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="SignatureMethodType")]
    public partial class SignatureMethodType
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", ElementName="HMACOutputLength")]
        public string HMACOutputLength;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI", AttributeName="Algorithm")]
        public string Algorithm;
        
        public SignatureMethodType()
        {
        }
        
        public SignatureMethodType(string hMACOutputLength, System.Xml.XmlNode[] any, string algorithm)
        {
            this.HMACOutputLength = hMACOutputLength;
            this.Any = any;
            this.Algorithm = algorithm;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="CanonicalizationMethodType")]
    public partial class CanonicalizationMethodType
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlNode[] Any;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI", AttributeName="Algorithm")]
        public string Algorithm;
        
        public CanonicalizationMethodType()
        {
        }
        
        public CanonicalizationMethodType(System.Xml.XmlNode[] any, string algorithm)
        {
            this.Any = any;
            this.Algorithm = algorithm;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="SignedInfoType")]
    public partial class SignedInfoType
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="CanonicalizationMethod")]
        public CanonicalizationMethodType CanonicalizationMethod;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="SignatureMethod")]
        public SignatureMethodType SignatureMethod;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("Reference")]
        public ReferenceType[] Reference;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID", AttributeName="Id")]
        public string Id;
        
        public SignedInfoType()
        {
        }
        
        public SignedInfoType(CanonicalizationMethodType canonicalizationMethod, SignatureMethodType signatureMethod, ReferenceType[] reference, string id)
        {
            this.CanonicalizationMethod = canonicalizationMethod;
            this.SignatureMethod = signatureMethod;
            this.Reference = reference;
            this.Id = id;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", TypeName="SignatureType")]
    public partial class SignatureType
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="SignedInfo")]
        public SignedInfoType SignedInfo;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="SignatureValue")]
        public SignatureValueType SignatureValue;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="KeyInfo")]
        public KeyInfoType KeyInfo;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("Object")]
        public ObjectType[] Object;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID", AttributeName="Id")]
        public string Id;
        
        public SignatureType()
        {
        }
        
        public SignatureType(SignedInfoType signedInfo, SignatureValueType signatureValue, KeyInfoType keyInfo, ObjectType[] @object, string id)
        {
            this.SignedInfo = signedInfo;
            this.SignatureValue = signatureValue;
            this.KeyInfo = keyInfo;
            this.Object = @object;
            this.Id = id;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ebxml.org/namespaces/messageHeader", TypeName="To")]
    public partial class To
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("PartyId")]
        public PartyId[] PartyId;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Role")]
        public string Role;
        
        public To()
        {
        }
        
        public To(PartyId[] partyId, string role)
        {
            this.PartyId = partyId;
            this.Role = role;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ebxml.org/namespaces/messageHeader", TypeName="Service")]
    public partial class Service
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, AttributeName="type")]
        public string type;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
        
        public Service()
        {
        }
        
        public Service(string type, string value)
        {
            this.type = type;
            this.Value = value;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ebxml.org/namespaces/messageHeader", TypeName="MessageData")]
    public partial class MessageData
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="MessageId")]
        public string MessageId;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Timestamp")]
        public string Timestamp;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="RefToMessageId")]
        public string RefToMessageId;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="TimeToLive")]
        public System.DateTime TimeToLive;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TimeToLiveSpecified;
        
        public MessageData()
        {
        }
        
        public MessageData(string messageId, string timestamp, string refToMessageId, System.DateTime timeToLive, bool timeToLiveSpecified)
        {
            this.MessageId = messageId;
            this.Timestamp = timestamp;
            this.RefToMessageId = refToMessageId;
            this.TimeToLive = timeToLive;
            this.TimeToLiveSpecified = timeToLiveSpecified;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.ebxml.org/namespaces/messageHeader", TypeName="Description")]
    public partial class Description
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://www.w3.org/XML/1998/namespace", AttributeName="lang")]
        public string lang;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
        
        public Description()
        {
        }
        
        public Description(string lang, string value)
        {
            this.lang = lang;
            this.Value = value;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.xmlsoap.org/ws/2002/12/secext", TypeName="Security")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.xmlsoap.org/ws/2002/12/secext", IsNullable=false)]
    public partial class Security : System.Web.Services.Protocols.SoapHeader
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="UsernameToken")]
        public SecurityUsernameToken UsernameToken;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="SabreAth")]
        public string SabreAth;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="BinarySecurityToken")]
        public string BinarySecurityToken;
        
        public Security()
        {
        }
        
        public Security(SecurityUsernameToken usernameToken, string sabreAth, string binarySecurityToken)
        {
            this.UsernameToken = usernameToken;
            this.SabreAth = sabreAth;
            this.BinarySecurityToken = binarySecurityToken;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://schemas.xmlsoap.org/ws/2002/12/secext", TypeName="SecurityUsernameToken")]
    public partial class SecurityUsernameToken
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Username")]
        public string Username;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Password")]
        public string Password;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("NewPassword")]
        public string[] NewPassword;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName="Organization")]
        public string Organization;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, ElementName="Domain")]
        public string Domain;
        
        public SecurityUsernameToken()
        {
        }
        
        public SecurityUsernameToken(string username, string password, string[] newPassword, string organization, string domain)
        {
            this.Username = username;
            this.Password = password;
            this.NewPassword = newPassword;
            this.Organization = organization;
            this.Domain = domain;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRQ")]
    public partial class AddRemarkRQ
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="POS")]
        public AddRemarkRQPOS POS;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="TPA_Extensions")]
        public AddRemarkRQTPA_Extensions TPA_Extensions;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("BasicRemark")]
        public AddRemarkRQBasicRemark[] BasicRemark;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("AlphaCodedRemark")]
        public AddRemarkRQAlphaCodedRemark[] AlphaCodedRemark;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("ClientAddressRemark")]
        public AddRemarkRQClientAddressRemark[] ClientAddressRemark;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("DeliveryAddressRemark")]
        public AddRemarkRQDeliveryAddressRemark[] DeliveryAddressRemark;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("InvoiceRemark")]
        public AddRemarkRQInvoiceRemark[] InvoiceRemark;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("ItineraryRemark")]
        public AddRemarkRQItineraryRemark[] ItineraryRemark;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="FOPRemark")]
        public AddRemarkRQFOPRemark FOPRemark;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("GroupNameRemark")]
        public AddRemarkRQGroupNameRemark[] GroupNameRemark;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("HistoricalRemark")]
        public AddRemarkRQHistoricalRemark[] HistoricalRemark;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("HiddenRemark")]
        public AddRemarkRQHiddenRemark[] HiddenRemark;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute("FutureQueuePlaceRemark")]
        public AddRemarkRQFutureQueuePlaceRemark[] FutureQueuePlaceRemark;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="CorporateNumberRemark")]
        public AddRemarkRQCorporateNumberRemark CorporateNumberRemark;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="EchoToken")]
        public string EchoToken;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="TimeStamp")]
        public string TimeStamp;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Target")]
        [System.ComponentModel.DefaultValueAttribute(AddRemarkRQTarget.Production)]
        public AddRemarkRQTarget Target;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Version")]
        public string Version;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger", AttributeName="SequenceNmbr")]
        public string SequenceNmbr;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="language", AttributeName="PrimaryLangID")]
        public string PrimaryLangID;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="language", AttributeName="AltLangID")]
        public string AltLangID;
        
        public AddRemarkRQ()
        {
            this.Target = AddRemarkRQTarget.Production;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRQPOS")]
    public partial class AddRemarkRQPOS
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Source")]
        public AddRemarkRQPOSSource Source;
        
        public AddRemarkRQPOS()
        {
        }
        
        public AddRemarkRQPOS(AddRemarkRQPOSSource source)
        {
            this.Source = source;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRQPOSSource")]
    public partial class AddRemarkRQPOSSource
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="RequestorID")]
        public AddRemarkRQPOSSourceRequestorID RequestorID;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Position")]
        public AddRemarkRQPOSSourcePosition Position;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="BookingChannel")]
        public AddRemarkRQPOSSourceBookingChannel BookingChannel;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="AgentSine")]
        public string AgentSine;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="PseudoCityCode")]
        public string PseudoCityCode;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="ISOCountry")]
        public string ISOCountry;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="ISOCurrency")]
        public string ISOCurrency;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="AgentDutyCode")]
        public string AgentDutyCode;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="AirlineVendorID")]
        public string AirlineVendorID;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="AirportCode")]
        public string AirportCode;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="FirstDepartPoint")]
        public string FirstDepartPoint;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="ERSP_UserID")]
        public string ERSP_UserID;
        
        public AddRemarkRQPOSSource()
        {
        }
        
        public AddRemarkRQPOSSource(AddRemarkRQPOSSourceRequestorID requestorID, AddRemarkRQPOSSourcePosition position, AddRemarkRQPOSSourceBookingChannel bookingChannel, string agentSine, string pseudoCityCode, string iSOCountry, string iSOCurrency, string agentDutyCode, string airlineVendorID, string airportCode, string firstDepartPoint, string eRSP_UserID)
        {
            this.RequestorID = requestorID;
            this.Position = position;
            this.BookingChannel = bookingChannel;
            this.AgentSine = agentSine;
            this.PseudoCityCode = pseudoCityCode;
            this.ISOCountry = iSOCountry;
            this.ISOCurrency = iSOCurrency;
            this.AgentDutyCode = agentDutyCode;
            this.AirlineVendorID = airlineVendorID;
            this.AirportCode = airportCode;
            this.FirstDepartPoint = firstDepartPoint;
            this.ERSP_UserID = eRSP_UserID;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRQPOSSourceRequestorID")]
    public partial class AddRemarkRQPOSSourceRequestorID
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="CompanyName")]
        public AddRemarkRQPOSSourceRequestorIDCompanyName CompanyName;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI", AttributeName="URL")]
        public string URL;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Type")]
        public string Type;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Instance")]
        public string Instance;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="ID")]
        public string ID;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="ID_Context")]
        public string ID_Context;
        
        public AddRemarkRQPOSSourceRequestorID()
        {
        }
        
        public AddRemarkRQPOSSourceRequestorID(AddRemarkRQPOSSourceRequestorIDCompanyName companyName, string uRL, string type, string instance, string iD, string iD_Context)
        {
            this.CompanyName = companyName;
            this.URL = uRL;
            this.Type = type;
            this.Instance = instance;
            this.ID = iD;
            this.ID_Context = iD_Context;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRQPOSSourceRequestorIDCompanyName")]
    public partial class AddRemarkRQPOSSourceRequestorIDCompanyName
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="CompanyShortName")]
        public string CompanyShortName;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="TravelSector")]
        public string TravelSector;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Code")]
        public string Code;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="CodeContext")]
        public string CodeContext;
        
        public AddRemarkRQPOSSourceRequestorIDCompanyName()
        {
        }
        
        public AddRemarkRQPOSSourceRequestorIDCompanyName(string companyShortName, string travelSector, string code, string codeContext)
        {
            this.CompanyShortName = companyShortName;
            this.TravelSector = travelSector;
            this.Code = code;
            this.CodeContext = codeContext;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRQPOSSourcePosition")]
    public partial class AddRemarkRQPOSSourcePosition
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Latitude")]
        public string Latitude;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Longitude")]
        public string Longitude;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Altitude")]
        public string Altitude;
        
        public AddRemarkRQPOSSourcePosition()
        {
        }
        
        public AddRemarkRQPOSSourcePosition(string latitude, string longitude, string altitude)
        {
            this.Latitude = latitude;
            this.Longitude = longitude;
            this.Altitude = altitude;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRQPOSSourceBookingChannel")]
    public partial class AddRemarkRQPOSSourceBookingChannel
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="CompanyName")]
        public AddRemarkRQPOSSourceBookingChannelCompanyName CompanyName;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Type")]
        public string Type;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Primary")]
        public bool Primary;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PrimarySpecified;
        
        public AddRemarkRQPOSSourceBookingChannel()
        {
        }
        
        public AddRemarkRQPOSSourceBookingChannel(AddRemarkRQPOSSourceBookingChannelCompanyName companyName, string type, bool primary, bool primarySpecified)
        {
            this.CompanyName = companyName;
            this.Type = type;
            this.Primary = primary;
            this.PrimarySpecified = primarySpecified;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRQPOSSourceBookingChannelCompanyName")]
    public partial class AddRemarkRQPOSSourceBookingChannelCompanyName
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="CompanyShortName")]
        public string CompanyShortName;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="TravelSector")]
        public string TravelSector;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Code")]
        public string Code;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="CodeContext")]
        public string CodeContext;
        
        public AddRemarkRQPOSSourceBookingChannelCompanyName()
        {
        }
        
        public AddRemarkRQPOSSourceBookingChannelCompanyName(string companyShortName, string travelSector, string code, string codeContext)
        {
            this.CompanyShortName = companyShortName;
            this.TravelSector = travelSector;
            this.Code = code;
            this.CodeContext = codeContext;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRQTPA_Extensions")]
    public partial class AddRemarkRQTPA_Extensions
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any;
        
        public AddRemarkRQTPA_Extensions()
        {
        }
        
        public AddRemarkRQTPA_Extensions(System.Xml.XmlElement[] any)
        {
            this.Any = any;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRQBasicRemark")]
    public partial class AddRemarkRQBasicRemark
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Text")]
        public string Text;
        
        public AddRemarkRQBasicRemark()
        {
        }
        
        public AddRemarkRQBasicRemark(string text)
        {
            this.Text = text;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRQAlphaCodedRemark")]
    public partial class AddRemarkRQAlphaCodedRemark
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Code")]
        public string Code;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Text")]
        public string Text;
        
        public AddRemarkRQAlphaCodedRemark()
        {
        }
        
        public AddRemarkRQAlphaCodedRemark(string code, string text)
        {
            this.Code = code;
            this.Text = text;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRQClientAddressRemark")]
    public partial class AddRemarkRQClientAddressRemark
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Text")]
        public string Text;
        
        public AddRemarkRQClientAddressRemark()
        {
        }
        
        public AddRemarkRQClientAddressRemark(string text)
        {
            this.Text = text;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRQDeliveryAddressRemark")]
    public partial class AddRemarkRQDeliveryAddressRemark
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Text")]
        public string Text;
        
        public AddRemarkRQDeliveryAddressRemark()
        {
        }
        
        public AddRemarkRQDeliveryAddressRemark(string text)
        {
            this.Text = text;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRQInvoiceRemark")]
    public partial class AddRemarkRQInvoiceRemark
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Text")]
        public string Text;
        
        public AddRemarkRQInvoiceRemark()
        {
        }
        
        public AddRemarkRQInvoiceRemark(string text)
        {
            this.Text = text;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRQItineraryRemark")]
    public partial class AddRemarkRQItineraryRemark
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Text")]
        public string Text;
        
        public AddRemarkRQItineraryRemark()
        {
        }
        
        public AddRemarkRQItineraryRemark(string text)
        {
            this.Text = text;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRQFOPRemark")]
    public partial class AddRemarkRQFOPRemark
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="CCInfo")]
        public AddRemarkRQFOPRemarkCCInfo CCInfo;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Type")]
        public string Type;
        
        public AddRemarkRQFOPRemark()
        {
        }
        
        public AddRemarkRQFOPRemark(AddRemarkRQFOPRemarkCCInfo cCInfo, string type)
        {
            this.CCInfo = cCInfo;
            this.Type = type;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRQFOPRemarkCCInfo")]
    public partial class AddRemarkRQFOPRemarkCCInfo
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="CreditCardVendor")]
        public AddRemarkRQFOPRemarkCCInfoCreditCardVendor CreditCardVendor;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="CreditCardNumber")]
        public AddRemarkRQFOPRemarkCCInfoCreditCardNumber CreditCardNumber;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="CreditCardExpiration")]
        public AddRemarkRQFOPRemarkCCInfoCreditCardExpiration CreditCardExpiration;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="SuppressCCInfo")]
        public AddRemarkRQFOPRemarkCCInfoSuppressCCInfo SuppressCCInfo;
        
        public AddRemarkRQFOPRemarkCCInfo()
        {
        }
        
        public AddRemarkRQFOPRemarkCCInfo(AddRemarkRQFOPRemarkCCInfoCreditCardVendor creditCardVendor, AddRemarkRQFOPRemarkCCInfoCreditCardNumber creditCardNumber, AddRemarkRQFOPRemarkCCInfoCreditCardExpiration creditCardExpiration, AddRemarkRQFOPRemarkCCInfoSuppressCCInfo suppressCCInfo)
        {
            this.CreditCardVendor = creditCardVendor;
            this.CreditCardNumber = creditCardNumber;
            this.CreditCardExpiration = creditCardExpiration;
            this.SuppressCCInfo = suppressCCInfo;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRQFOPRemarkCCInfoCreditCardVendor")]
    public partial class AddRemarkRQFOPRemarkCCInfoCreditCardVendor
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Code")]
        public string Code;
        
        public AddRemarkRQFOPRemarkCCInfoCreditCardVendor()
        {
        }
        
        public AddRemarkRQFOPRemarkCCInfoCreditCardVendor(string code)
        {
            this.Code = code;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRQFOPRemarkCCInfoCreditCardNumber")]
    public partial class AddRemarkRQFOPRemarkCCInfoCreditCardNumber
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Code")]
        public string Code;
        
        public AddRemarkRQFOPRemarkCCInfoCreditCardNumber()
        {
        }
        
        public AddRemarkRQFOPRemarkCCInfoCreditCardNumber(string code)
        {
            this.Code = code;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRQFOPRemarkCCInfoCreditCardExpiration")]
    public partial class AddRemarkRQFOPRemarkCCInfoCreditCardExpiration
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="ExpireDate")]
        public string ExpireDate;
        
        public AddRemarkRQFOPRemarkCCInfoCreditCardExpiration()
        {
        }
        
        public AddRemarkRQFOPRemarkCCInfoCreditCardExpiration(string expireDate)
        {
            this.ExpireDate = expireDate;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRQFOPRemarkCCInfoSuppressCCInfo")]
    public partial class AddRemarkRQFOPRemarkCCInfoSuppressCCInfo
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Code")]
        public string Code;
        
        public AddRemarkRQFOPRemarkCCInfoSuppressCCInfo()
        {
        }
        
        public AddRemarkRQFOPRemarkCCInfoSuppressCCInfo(string code)
        {
            this.Code = code;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRQGroupNameRemark")]
    public partial class AddRemarkRQGroupNameRemark
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Text")]
        public string Text;
        
        public AddRemarkRQGroupNameRemark()
        {
        }
        
        public AddRemarkRQGroupNameRemark(string text)
        {
            this.Text = text;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRQHistoricalRemark")]
    public partial class AddRemarkRQHistoricalRemark
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Text")]
        public string Text;
        
        public AddRemarkRQHistoricalRemark()
        {
        }
        
        public AddRemarkRQHistoricalRemark(string text)
        {
            this.Text = text;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRQHiddenRemark")]
    public partial class AddRemarkRQHiddenRemark
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Text")]
        public string Text;
        
        public AddRemarkRQHiddenRemark()
        {
        }
        
        public AddRemarkRQHiddenRemark(string text)
        {
            this.Text = text;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRQFutureQueuePlaceRemark")]
    public partial class AddRemarkRQFutureQueuePlaceRemark
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="PseudoCityCode")]
        public string PseudoCityCode;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date", AttributeName="Date")]
        public System.DateTime Date;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DateSpecified;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer", AttributeName="QueueIdentifier")]
        public string QueueIdentifier;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer", AttributeName="PICCode")]
        public string PICCode;
        
        public AddRemarkRQFutureQueuePlaceRemark()
        {
        }
        
        public AddRemarkRQFutureQueuePlaceRemark(string pseudoCityCode, System.DateTime date, bool dateSpecified, string queueIdentifier, string pICCode)
        {
            this.PseudoCityCode = pseudoCityCode;
            this.Date = date;
            this.DateSpecified = dateSpecified;
            this.QueueIdentifier = queueIdentifier;
            this.PICCode = pICCode;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRQCorporateNumberRemark")]
    public partial class AddRemarkRQCorporateNumberRemark
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Text")]
        public string Text;
        
        public AddRemarkRQCorporateNumberRemark()
        {
        }
        
        public AddRemarkRQCorporateNumberRemark(string text)
        {
            this.Text = text;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRQTarget")]
    public enum AddRemarkRQTarget
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="Test")]
        Test,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="Production")]
        Production,
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRS")]
    public partial class AddRemarkRS
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Success")]
        public object Success;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Warnings")]
        public AddRemarkRSWarnings Warnings;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="TPA_Extensions")]
        public AddRemarkRSTPA_Extensions TPA_Extensions;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Errors")]
        public AddRemarkRSErrors Errors;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="EchoToken")]
        public string EchoToken;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="TimeStamp")]
        public string TimeStamp;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Target")]
        [System.ComponentModel.DefaultValueAttribute(AddRemarkRSTarget.Production)]
        public AddRemarkRSTarget Target;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Version")]
        public string Version;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="nonNegativeInteger", AttributeName="SequenceNmbr")]
        public string SequenceNmbr;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="language", AttributeName="PrimaryLangID")]
        public string PrimaryLangID;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="language", AttributeName="AltLangID")]
        public string AltLangID;
        
        public AddRemarkRS()
        {
            this.Target = AddRemarkRSTarget.Production;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRSWarnings")]
    public partial class AddRemarkRSWarnings
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Warning")]
        public AddRemarkRSWarningsWarning Warning;
        
        public AddRemarkRSWarnings()
        {
        }
        
        public AddRemarkRSWarnings(AddRemarkRSWarningsWarning warning)
        {
            this.Warning = warning;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRSWarningsWarning")]
    public partial class AddRemarkRSWarningsWarning
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Language")]
        public string Language;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="ShortText")]
        public string ShortText;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Type")]
        public string Type;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Code")]
        public string Code;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI", AttributeName="DocURL")]
        public string DocURL;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Status")]
        public string Status;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Tag")]
        public string Tag;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="RecordID")]
        public string RecordID;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value;
        
        public AddRemarkRSWarningsWarning()
        {
        }
        
        public AddRemarkRSWarningsWarning(string language, string shortText, string type, string code, string docURL, string status, string tag, string recordID, string value)
        {
            this.Language = language;
            this.ShortText = shortText;
            this.Type = type;
            this.Code = code;
            this.DocURL = docURL;
            this.Status = status;
            this.Tag = tag;
            this.RecordID = recordID;
            this.Value = value;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRSTPA_Extensions")]
    public partial class AddRemarkRSTPA_Extensions
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="HostCommand")]
        public string HostCommand;
        
        public AddRemarkRSTPA_Extensions()
        {
        }
        
        public AddRemarkRSTPA_Extensions(string hostCommand)
        {
            this.HostCommand = hostCommand;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRSErrors")]
    public partial class AddRemarkRSErrors
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Error")]
        public AddRemarkRSErrorsError Error;
        
        public AddRemarkRSErrors()
        {
        }
        
        public AddRemarkRSErrors(AddRemarkRSErrorsError error)
        {
            this.Error = error;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRSErrorsError")]
    public partial class AddRemarkRSErrorsError
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="ErrorInfo")]
        public AddRemarkRSErrorsErrorErrorInfo ErrorInfo;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="ErrorCode")]
        public string ErrorCode;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="Severity")]
        public string Severity;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute(AttributeName="ErrorMessage")]
        public string ErrorMessage;
        
        public AddRemarkRSErrorsError()
        {
        }
        
        public AddRemarkRSErrorsError(AddRemarkRSErrorsErrorErrorInfo errorInfo, string errorCode, string severity, string errorMessage)
        {
            this.ErrorInfo = errorInfo;
            this.ErrorCode = errorCode;
            this.Severity = severity;
            this.ErrorMessage = errorMessage;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRSErrorsErrorErrorInfo")]
    public partial class AddRemarkRSErrorsErrorErrorInfo
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(ElementName="Message")]
        public string Message;
        
        public AddRemarkRSErrorsErrorErrorInfo()
        {
        }
        
        public AddRemarkRSErrorsErrorErrorInfo(string message)
        {
            this.Message = message;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.312")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://webservices.sabre.com/sabreXML/2003/07", TypeName="AddRemarkRSTarget")]
    public enum AddRemarkRSTarget
    {
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="Test")]
        Test,
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlEnumAttribute(Name="Production")]
        Production,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    public delegate void AddRemarkRQCompletedEventHandler(object sender, AddRemarkRQCompletedEventArgs e);
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.312")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddRemarkRQCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {
        
        private object[] results;
        
        internal AddRemarkRQCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState)
        {
            this.results = results;
        }
        
        /// <remarks/>
        public AddRemarkRS Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((AddRemarkRS)(this.results[0]));
            }
        }
    }
}
