//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
// 
#pragma warning disable 1591

namespace Ssoft.Pages.PagosOnlineWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PagosOnLineWSSoap", Namespace="http://tempuri.org/")]
    public partial class PagosOnLineWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ConsultarTiposMediosPagoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarMediosPagoOperationCompleted;
        
        private System.Threading.SendOrPostCallback SolicitarAutorizacionConDispersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback SolicitarTransaccionPSEOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarAerolineasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ValidarAerolineasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarBancosPSEOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarTransaccionesPendientesPSEOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PagosOnLineWS() {
            this.Url = global::Ssoft.Pages.Properties.Settings.Default.Ssoft_Pages_PagosOnlineWS_PagosOnLineWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ConsultarTiposMediosPagoCompletedEventHandler ConsultarTiposMediosPagoCompleted;
        
        /// <remarks/>
        public event ConsultarMediosPagoCompletedEventHandler ConsultarMediosPagoCompleted;
        
        /// <remarks/>
        public event SolicitarAutorizacionConDispersionCompletedEventHandler SolicitarAutorizacionConDispersionCompleted;
        
        /// <remarks/>
        public event SolicitarTransaccionPSECompletedEventHandler SolicitarTransaccionPSECompleted;
        
        /// <remarks/>
        public event ConsultarAerolineasCompletedEventHandler ConsultarAerolineasCompleted;
        
        /// <remarks/>
        public event ValidarAerolineasCompletedEventHandler ValidarAerolineasCompleted;
        
        /// <remarks/>
        public event ConsultarBancosPSECompletedEventHandler ConsultarBancosPSECompleted;
        
        /// <remarks/>
        public event ConsultarTransaccionesPendientesPSECompletedEventHandler ConsultarTransaccionesPendientesPSECompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarTiposMediosPago", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ConsultarTiposMediosPago(string sUsuarioId) {
            object[] results = this.Invoke("ConsultarTiposMediosPago", new object[] {
                        sUsuarioId});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarTiposMediosPagoAsync(string sUsuarioId) {
            this.ConsultarTiposMediosPagoAsync(sUsuarioId, null);
        }
        
        /// <remarks/>
        public void ConsultarTiposMediosPagoAsync(string sUsuarioId, object userState) {
            if ((this.ConsultarTiposMediosPagoOperationCompleted == null)) {
                this.ConsultarTiposMediosPagoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarTiposMediosPagoOperationCompleted);
            }
            this.InvokeAsync("ConsultarTiposMediosPago", new object[] {
                        sUsuarioId}, this.ConsultarTiposMediosPagoOperationCompleted, userState);
        }
        
        private void OnConsultarTiposMediosPagoOperationCompleted(object arg) {
            if ((this.ConsultarTiposMediosPagoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarTiposMediosPagoCompleted(this, new ConsultarTiposMediosPagoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarMediosPago", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ConsultarMediosPago(string sUsuarioId, string sTipoMedioPago) {
            object[] results = this.Invoke("ConsultarMediosPago", new object[] {
                        sUsuarioId,
                        sTipoMedioPago});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarMediosPagoAsync(string sUsuarioId, string sTipoMedioPago) {
            this.ConsultarMediosPagoAsync(sUsuarioId, sTipoMedioPago, null);
        }
        
        /// <remarks/>
        public void ConsultarMediosPagoAsync(string sUsuarioId, string sTipoMedioPago, object userState) {
            if ((this.ConsultarMediosPagoOperationCompleted == null)) {
                this.ConsultarMediosPagoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarMediosPagoOperationCompleted);
            }
            this.InvokeAsync("ConsultarMediosPago", new object[] {
                        sUsuarioId,
                        sTipoMedioPago}, this.ConsultarMediosPagoOperationCompleted, userState);
        }
        
        private void OnConsultarMediosPagoOperationCompleted(object arg) {
            if ((this.ConsultarMediosPagoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarMediosPagoCompleted(this, new ConsultarMediosPagoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SolicitarAutorizacionConDispersion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] SolicitarAutorizacionConDispersion(
                    string sUsuarioId, 
                    string sRefVenta, 
                    string sDescripcion, 
                    decimal dValor, 
                    decimal dIva, 
                    decimal dBaseDevolucion, 
                    decimal dValorAdicional, 
                    decimal dTA, 
                    decimal dIvaTA, 
                    decimal dBaseTA, 
                    string sMonedaIso, 
                    int iCuotas, 
                    string sNombreComprador, 
                    string sDocumentoComprador, 
                    string sEmailComprador, 
                    string sTelComprador, 
                    string sTelOficinaComprador, 
                    string sPaisCorrespondencia, 
                    string sCiudadCorrespondencia, 
                    string sDireccionCorrespondencia, 
                    string sPaisEnvio, 
                    string sCiudadEnvio, 
                    string sDireccionEnvio, 
                    string sIpComprador, 
                    string sMedioPago, 
                    string sAerolinea, 
                    string sExtra1, 
                    string sExtra2, 
                    string sNumTarjeta, 
                    string sNombreTarjetaHabiente, 
                    string sFechaExpiracion, 
                    string sCodSeguridad, 
                    string sCookie, 
                    string sUserAgent, 
                    bool bMAF, 
                    bool bReportarPagConfirmacion) {
            object[] results = this.Invoke("SolicitarAutorizacionConDispersion", new object[] {
                        sUsuarioId,
                        sRefVenta,
                        sDescripcion,
                        dValor,
                        dIva,
                        dBaseDevolucion,
                        dValorAdicional,
                        dTA,
                        dIvaTA,
                        dBaseTA,
                        sMonedaIso,
                        iCuotas,
                        sNombreComprador,
                        sDocumentoComprador,
                        sEmailComprador,
                        sTelComprador,
                        sTelOficinaComprador,
                        sPaisCorrespondencia,
                        sCiudadCorrespondencia,
                        sDireccionCorrespondencia,
                        sPaisEnvio,
                        sCiudadEnvio,
                        sDireccionEnvio,
                        sIpComprador,
                        sMedioPago,
                        sAerolinea,
                        sExtra1,
                        sExtra2,
                        sNumTarjeta,
                        sNombreTarjetaHabiente,
                        sFechaExpiracion,
                        sCodSeguridad,
                        sCookie,
                        sUserAgent,
                        bMAF,
                        bReportarPagConfirmacion});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void SolicitarAutorizacionConDispersionAsync(
                    string sUsuarioId, 
                    string sRefVenta, 
                    string sDescripcion, 
                    decimal dValor, 
                    decimal dIva, 
                    decimal dBaseDevolucion, 
                    decimal dValorAdicional, 
                    decimal dTA, 
                    decimal dIvaTA, 
                    decimal dBaseTA, 
                    string sMonedaIso, 
                    int iCuotas, 
                    string sNombreComprador, 
                    string sDocumentoComprador, 
                    string sEmailComprador, 
                    string sTelComprador, 
                    string sTelOficinaComprador, 
                    string sPaisCorrespondencia, 
                    string sCiudadCorrespondencia, 
                    string sDireccionCorrespondencia, 
                    string sPaisEnvio, 
                    string sCiudadEnvio, 
                    string sDireccionEnvio, 
                    string sIpComprador, 
                    string sMedioPago, 
                    string sAerolinea, 
                    string sExtra1, 
                    string sExtra2, 
                    string sNumTarjeta, 
                    string sNombreTarjetaHabiente, 
                    string sFechaExpiracion, 
                    string sCodSeguridad, 
                    string sCookie, 
                    string sUserAgent, 
                    bool bMAF, 
                    bool bReportarPagConfirmacion) {
            this.SolicitarAutorizacionConDispersionAsync(sUsuarioId, sRefVenta, sDescripcion, dValor, dIva, dBaseDevolucion, dValorAdicional, dTA, dIvaTA, dBaseTA, sMonedaIso, iCuotas, sNombreComprador, sDocumentoComprador, sEmailComprador, sTelComprador, sTelOficinaComprador, sPaisCorrespondencia, sCiudadCorrespondencia, sDireccionCorrespondencia, sPaisEnvio, sCiudadEnvio, sDireccionEnvio, sIpComprador, sMedioPago, sAerolinea, sExtra1, sExtra2, sNumTarjeta, sNombreTarjetaHabiente, sFechaExpiracion, sCodSeguridad, sCookie, sUserAgent, bMAF, bReportarPagConfirmacion, null);
        }
        
        /// <remarks/>
        public void SolicitarAutorizacionConDispersionAsync(
                    string sUsuarioId, 
                    string sRefVenta, 
                    string sDescripcion, 
                    decimal dValor, 
                    decimal dIva, 
                    decimal dBaseDevolucion, 
                    decimal dValorAdicional, 
                    decimal dTA, 
                    decimal dIvaTA, 
                    decimal dBaseTA, 
                    string sMonedaIso, 
                    int iCuotas, 
                    string sNombreComprador, 
                    string sDocumentoComprador, 
                    string sEmailComprador, 
                    string sTelComprador, 
                    string sTelOficinaComprador, 
                    string sPaisCorrespondencia, 
                    string sCiudadCorrespondencia, 
                    string sDireccionCorrespondencia, 
                    string sPaisEnvio, 
                    string sCiudadEnvio, 
                    string sDireccionEnvio, 
                    string sIpComprador, 
                    string sMedioPago, 
                    string sAerolinea, 
                    string sExtra1, 
                    string sExtra2, 
                    string sNumTarjeta, 
                    string sNombreTarjetaHabiente, 
                    string sFechaExpiracion, 
                    string sCodSeguridad, 
                    string sCookie, 
                    string sUserAgent, 
                    bool bMAF, 
                    bool bReportarPagConfirmacion, 
                    object userState) {
            if ((this.SolicitarAutorizacionConDispersionOperationCompleted == null)) {
                this.SolicitarAutorizacionConDispersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSolicitarAutorizacionConDispersionOperationCompleted);
            }
            this.InvokeAsync("SolicitarAutorizacionConDispersion", new object[] {
                        sUsuarioId,
                        sRefVenta,
                        sDescripcion,
                        dValor,
                        dIva,
                        dBaseDevolucion,
                        dValorAdicional,
                        dTA,
                        dIvaTA,
                        dBaseTA,
                        sMonedaIso,
                        iCuotas,
                        sNombreComprador,
                        sDocumentoComprador,
                        sEmailComprador,
                        sTelComprador,
                        sTelOficinaComprador,
                        sPaisCorrespondencia,
                        sCiudadCorrespondencia,
                        sDireccionCorrespondencia,
                        sPaisEnvio,
                        sCiudadEnvio,
                        sDireccionEnvio,
                        sIpComprador,
                        sMedioPago,
                        sAerolinea,
                        sExtra1,
                        sExtra2,
                        sNumTarjeta,
                        sNombreTarjetaHabiente,
                        sFechaExpiracion,
                        sCodSeguridad,
                        sCookie,
                        sUserAgent,
                        bMAF,
                        bReportarPagConfirmacion}, this.SolicitarAutorizacionConDispersionOperationCompleted, userState);
        }
        
        private void OnSolicitarAutorizacionConDispersionOperationCompleted(object arg) {
            if ((this.SolicitarAutorizacionConDispersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SolicitarAutorizacionConDispersionCompleted(this, new SolicitarAutorizacionConDispersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SolicitarTransaccionPSE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] SolicitarTransaccionPSE(
                    string sUsuarioId, 
                    string sRefVenta, 
                    string sDescripcion, 
                    decimal dValor, 
                    decimal dIva, 
                    string sNombreComprador, 
                    string sDocumentoComprador, 
                    string sEmailComprador, 
                    string sTelComprador, 
                    string sTelOficinaComprador, 
                    string sPaisCorrespondencia, 
                    string sCiudadCorrespondencia, 
                    string sDireccionCorrespondencia, 
                    string sIpComprador, 
                    string sExtra1, 
                    string sExtra2, 
                    string sCodBancoPse, 
                    string sTipoCliente, 
                    string sReferencia1, 
                    string sReferencia2, 
                    string sReferencia3, 
                    string sCookie, 
                    string sUserAgent) {
            object[] results = this.Invoke("SolicitarTransaccionPSE", new object[] {
                        sUsuarioId,
                        sRefVenta,
                        sDescripcion,
                        dValor,
                        dIva,
                        sNombreComprador,
                        sDocumentoComprador,
                        sEmailComprador,
                        sTelComprador,
                        sTelOficinaComprador,
                        sPaisCorrespondencia,
                        sCiudadCorrespondencia,
                        sDireccionCorrespondencia,
                        sIpComprador,
                        sExtra1,
                        sExtra2,
                        sCodBancoPse,
                        sTipoCliente,
                        sReferencia1,
                        sReferencia2,
                        sReferencia3,
                        sCookie,
                        sUserAgent});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void SolicitarTransaccionPSEAsync(
                    string sUsuarioId, 
                    string sRefVenta, 
                    string sDescripcion, 
                    decimal dValor, 
                    decimal dIva, 
                    string sNombreComprador, 
                    string sDocumentoComprador, 
                    string sEmailComprador, 
                    string sTelComprador, 
                    string sTelOficinaComprador, 
                    string sPaisCorrespondencia, 
                    string sCiudadCorrespondencia, 
                    string sDireccionCorrespondencia, 
                    string sIpComprador, 
                    string sExtra1, 
                    string sExtra2, 
                    string sCodBancoPse, 
                    string sTipoCliente, 
                    string sReferencia1, 
                    string sReferencia2, 
                    string sReferencia3, 
                    string sCookie, 
                    string sUserAgent) {
            this.SolicitarTransaccionPSEAsync(sUsuarioId, sRefVenta, sDescripcion, dValor, dIva, sNombreComprador, sDocumentoComprador, sEmailComprador, sTelComprador, sTelOficinaComprador, sPaisCorrespondencia, sCiudadCorrespondencia, sDireccionCorrespondencia, sIpComprador, sExtra1, sExtra2, sCodBancoPse, sTipoCliente, sReferencia1, sReferencia2, sReferencia3, sCookie, sUserAgent, null);
        }
        
        /// <remarks/>
        public void SolicitarTransaccionPSEAsync(
                    string sUsuarioId, 
                    string sRefVenta, 
                    string sDescripcion, 
                    decimal dValor, 
                    decimal dIva, 
                    string sNombreComprador, 
                    string sDocumentoComprador, 
                    string sEmailComprador, 
                    string sTelComprador, 
                    string sTelOficinaComprador, 
                    string sPaisCorrespondencia, 
                    string sCiudadCorrespondencia, 
                    string sDireccionCorrespondencia, 
                    string sIpComprador, 
                    string sExtra1, 
                    string sExtra2, 
                    string sCodBancoPse, 
                    string sTipoCliente, 
                    string sReferencia1, 
                    string sReferencia2, 
                    string sReferencia3, 
                    string sCookie, 
                    string sUserAgent, 
                    object userState) {
            if ((this.SolicitarTransaccionPSEOperationCompleted == null)) {
                this.SolicitarTransaccionPSEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSolicitarTransaccionPSEOperationCompleted);
            }
            this.InvokeAsync("SolicitarTransaccionPSE", new object[] {
                        sUsuarioId,
                        sRefVenta,
                        sDescripcion,
                        dValor,
                        dIva,
                        sNombreComprador,
                        sDocumentoComprador,
                        sEmailComprador,
                        sTelComprador,
                        sTelOficinaComprador,
                        sPaisCorrespondencia,
                        sCiudadCorrespondencia,
                        sDireccionCorrespondencia,
                        sIpComprador,
                        sExtra1,
                        sExtra2,
                        sCodBancoPse,
                        sTipoCliente,
                        sReferencia1,
                        sReferencia2,
                        sReferencia3,
                        sCookie,
                        sUserAgent}, this.SolicitarTransaccionPSEOperationCompleted, userState);
        }
        
        private void OnSolicitarTransaccionPSEOperationCompleted(object arg) {
            if ((this.SolicitarTransaccionPSECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SolicitarTransaccionPSECompleted(this, new SolicitarTransaccionPSECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarAerolineas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ConsultarAerolineas(string sUsuarioId) {
            object[] results = this.Invoke("ConsultarAerolineas", new object[] {
                        sUsuarioId});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarAerolineasAsync(string sUsuarioId) {
            this.ConsultarAerolineasAsync(sUsuarioId, null);
        }
        
        /// <remarks/>
        public void ConsultarAerolineasAsync(string sUsuarioId, object userState) {
            if ((this.ConsultarAerolineasOperationCompleted == null)) {
                this.ConsultarAerolineasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarAerolineasOperationCompleted);
            }
            this.InvokeAsync("ConsultarAerolineas", new object[] {
                        sUsuarioId}, this.ConsultarAerolineasOperationCompleted, userState);
        }
        
        private void OnConsultarAerolineasOperationCompleted(object arg) {
            if ((this.ConsultarAerolineasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarAerolineasCompleted(this, new ConsultarAerolineasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ValidarAerolineas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ValidarAerolineas(string sUsuarioId) {
            this.Invoke("ValidarAerolineas", new object[] {
                        sUsuarioId});
        }
        
        /// <remarks/>
        public void ValidarAerolineasAsync(string sUsuarioId) {
            this.ValidarAerolineasAsync(sUsuarioId, null);
        }
        
        /// <remarks/>
        public void ValidarAerolineasAsync(string sUsuarioId, object userState) {
            if ((this.ValidarAerolineasOperationCompleted == null)) {
                this.ValidarAerolineasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidarAerolineasOperationCompleted);
            }
            this.InvokeAsync("ValidarAerolineas", new object[] {
                        sUsuarioId}, this.ValidarAerolineasOperationCompleted, userState);
        }
        
        private void OnValidarAerolineasOperationCompleted(object arg) {
            if ((this.ValidarAerolineasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidarAerolineasCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarBancosPSE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ConsultarBancosPSE(string sUsuarioId) {
            object[] results = this.Invoke("ConsultarBancosPSE", new object[] {
                        sUsuarioId});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarBancosPSEAsync(string sUsuarioId) {
            this.ConsultarBancosPSEAsync(sUsuarioId, null);
        }
        
        /// <remarks/>
        public void ConsultarBancosPSEAsync(string sUsuarioId, object userState) {
            if ((this.ConsultarBancosPSEOperationCompleted == null)) {
                this.ConsultarBancosPSEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarBancosPSEOperationCompleted);
            }
            this.InvokeAsync("ConsultarBancosPSE", new object[] {
                        sUsuarioId}, this.ConsultarBancosPSEOperationCompleted, userState);
        }
        
        private void OnConsultarBancosPSEOperationCompleted(object arg) {
            if ((this.ConsultarBancosPSECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarBancosPSECompleted(this, new ConsultarBancosPSECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarTransaccionesPendientesPSE", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultarTransaccionesPendientesPSE(string sDocumentoComprador, string sUsuarioId) {
            object[] results = this.Invoke("ConsultarTransaccionesPendientesPSE", new object[] {
                        sDocumentoComprador,
                        sUsuarioId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarTransaccionesPendientesPSEAsync(string sDocumentoComprador, string sUsuarioId) {
            this.ConsultarTransaccionesPendientesPSEAsync(sDocumentoComprador, sUsuarioId, null);
        }
        
        /// <remarks/>
        public void ConsultarTransaccionesPendientesPSEAsync(string sDocumentoComprador, string sUsuarioId, object userState) {
            if ((this.ConsultarTransaccionesPendientesPSEOperationCompleted == null)) {
                this.ConsultarTransaccionesPendientesPSEOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarTransaccionesPendientesPSEOperationCompleted);
            }
            this.InvokeAsync("ConsultarTransaccionesPendientesPSE", new object[] {
                        sDocumentoComprador,
                        sUsuarioId}, this.ConsultarTransaccionesPendientesPSEOperationCompleted, userState);
        }
        
        private void OnConsultarTransaccionesPendientesPSEOperationCompleted(object arg) {
            if ((this.ConsultarTransaccionesPendientesPSECompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarTransaccionesPendientesPSECompleted(this, new ConsultarTransaccionesPendientesPSECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ConsultarTiposMediosPagoCompletedEventHandler(object sender, ConsultarTiposMediosPagoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarTiposMediosPagoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarTiposMediosPagoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ConsultarMediosPagoCompletedEventHandler(object sender, ConsultarMediosPagoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarMediosPagoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarMediosPagoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SolicitarAutorizacionConDispersionCompletedEventHandler(object sender, SolicitarAutorizacionConDispersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SolicitarAutorizacionConDispersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SolicitarAutorizacionConDispersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void SolicitarTransaccionPSECompletedEventHandler(object sender, SolicitarTransaccionPSECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SolicitarTransaccionPSECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SolicitarTransaccionPSECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ConsultarAerolineasCompletedEventHandler(object sender, ConsultarAerolineasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarAerolineasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarAerolineasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ValidarAerolineasCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ConsultarBancosPSECompletedEventHandler(object sender, ConsultarBancosPSECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarBancosPSECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarBancosPSECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ConsultarTransaccionesPendientesPSECompletedEventHandler(object sender, ConsultarTransaccionesPendientesPSECompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarTransaccionesPendientesPSECompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarTransaccionesPendientesPSECompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591