//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18052
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_SsoftSabre.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")]
        public string WS_SsoftSabre_OTA_AirRules_OTA_AirRulesService {
            get {
                return ((string)(this["WS_SsoftSabre_OTA_AirRules_OTA_AirRulesService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")]
        public string WS_SsoftSabre_SabreCommandLLS_SabreCommandLLSService {
            get {
                return ((string)(this["WS_SsoftSabre_SabreCommandLLS_SabreCommandLLSService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")]
        public string WS_SsoftSabre_OTA_AirLowFareSearch_OTA_AirLowFareSearchService {
            get {
                return ((string)(this["WS_SsoftSabre_OTA_AirLowFareSearch_OTA_AirLowFareSearchService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")]
        public string WS_SsoftSabre_SessionClose_SessionCloseRQService {
            get {
                return ((string)(this["WS_SsoftSabre_SessionClose_SessionCloseRQService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")]
        public string WS_SsoftSabre_SessionCreateRQ_SessionCreateRQService {
            get {
                return ((string)(this["WS_SsoftSabre_SessionCreateRQ_SessionCreateRQService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")]
        public string WS_SsoftSabre_OTA_AirPrice_OTA_AirPriceService {
            get {
                return ((string)(this["WS_SsoftSabre_OTA_AirPrice_OTA_AirPriceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")]
        public string WS_SsoftSabre_SessionValidate_SessionValidateRQService {
            get {
                return ((string)(this["WS_SsoftSabre_SessionValidate_SessionValidateRQService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")]
        public string WS_SsoftSabre_EndTransactionRQ1_EndTransactionService {
            get {
                return ((string)(this["WS_SsoftSabre_EndTransactionRQ1_EndTransactionService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://cert.webservices.sabre.com/websvc")]
        public string WS_SsoftSabre_RulesFromPriceRQ_RulesFromPriceService {
            get {
                return ((string)(this["WS_SsoftSabre_RulesFromPriceRQ_RulesFromPriceService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")]
        public string WS_SsoftSabre_OTA_TravelItineraryRead_OTA_TravelItineraryService {
            get {
                return ((string)(this["WS_SsoftSabre_OTA_TravelItineraryRead_OTA_TravelItineraryService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")]
        public string WS_SsoftSabre_OTA_Cancel_OTA_CancelService {
            get {
                return ((string)(this["WS_SsoftSabre_OTA_Cancel_OTA_CancelService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")]
        public string WS_SsoftSabre_OTA_AirBook_OTA_AirBookService {
            get {
                return ((string)(this["WS_SsoftSabre_OTA_AirBook_OTA_AirBookService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")]
        public string WS_SsoftSabre_OTA_AirAvail_OTA_AirAvailService {
            get {
                return ((string)(this["WS_SsoftSabre_OTA_AirAvail_OTA_AirAvailService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")]
        public string WS_SsoftSabre_ShortSell_ShortSellService {
            get {
                return ((string)(this["WS_SsoftSabre_ShortSell_ShortSellService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")]
        public string WS_SsoftSabre_BargainFinderPlus_BargainFinderPlusService {
            get {
                return ((string)(this["WS_SsoftSabre_BargainFinderPlus_BargainFinderPlusService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")]
        public string WS_SsoftSabre_DisplayPriceQuote_DisplayPriceQuoteService {
            get {
                return ((string)(this["WS_SsoftSabre_DisplayPriceQuote_DisplayPriceQuoteService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")]
        public string WS_SsoftSabre_DesignatePrinterRQ_DesignatePrinterService {
            get {
                return ((string)(this["WS_SsoftSabre_DesignatePrinterRQ_DesignatePrinterService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")]
        public string WS_SsoftSabre_AirTicketRQ_AirTicketService {
            get {
                return ((string)(this["WS_SsoftSabre_AirTicketRQ_AirTicketService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://webservices.sabre.com/websvc")]
        public string WS_SsoftSabre_SWS_BargainFinderMaxRQ_BargainFinderMaxService {
            get {
                return ((string)(this["WS_SsoftSabre_SWS_BargainFinderMaxRQ_BargainFinderMaxService"]));
            }
        }
    }
}
